version: "3"
services:

  cupsd:
    image: ghcr.io/groskopf/printerbox_cupsd:v2
#    build:
#      context: ../printerbox_cupsd
#      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /dev:/dev 
      - /var/run/dbus:/var/run/dbus
    tmpfs:
      - /tmp
      - /run
      - /var/log
      - /var/spool
      - /var/cache
    entrypoint: /scripts/start_cupsd.sh
    networks:
      - printerbox_network
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  client:
    image: ghcr.io/groskopf/printerbox_client:v2.1
#    build:
#      context: ../printerbox_client
#      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /dev:/dev 
      - ./config:/app/config 
      - printer_labels:/labels
    entrypoint: python
    command: /app/src/main.py
    working_dir: /app
    networks:
      - printerbox_network
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  sortkaffe:
    image: ghcr.io/groskopf/printerbox_sortkaffe:v2.2
 #   build:
 #     context: ../printerbox_sortkaffe
 #     dockerfile: Dockerfile
    privileged: true
    volumes:
      - /dev:/dev 
      - ./config:/config 
      - printer_labels:/labels
    entrypoint: python
    command: /app/src/printerbox.py
    networks:
      - printerbox_network
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  printerbox_network:

volumes:
  printer_labels:
    external: true

